'use strict'
const express = require('express')
const bodyParser = require('body-parser')
const app = express()
app.use(bodyParser.urlencoded({ extended: false }))
app.use(bodyParser.json())
app.set('view engine', 'ejs')
const index = require('./routes/index.js')
const teacher = require('./routes/teacher.js')
const subject = require('./routes/subject')
const student = require('./routes/student')

app.use('/', index)
app.use('/teachers', teacher)
app.use('/subjects', subject)
app.use('/students', student)
app.listen(3000)
